fix(build&push): fix back and front

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -88,9 +88,14 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and Push Backend Image
+        env:
+          NEW_VERSION: ${{ env.NEW_VERSION }}
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.NEW_VERSION }} -f backend/Dockerfile ./backend
-          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ env.NEW_VERSION }}
+          if [ -z "$NEW_VERSION" ]; then
+            echo "Error: Version not set." && exit 1
+          fi
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$NEW_VERSION -f backend/Dockerfile ./backend
+          docker push ${{ secrets.DOCKER_USERNAME }}/backend:$NEW_VERSION
 
   build_and_push_frontend:
     needs: determine_version
@@ -111,6 +116,11 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and Push Frontend Image
+        env:
+          NEW_VERSION: ${{ env.NEW_VERSION }}
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.NEW_VERSION }} -f frontend/Dockerfile ./frontend
-          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ env.NEW_VERSION }}
+          if [ -z "$NEW_VERSION" ]; then
+            echo "Error: Version not set." && exit 1
+          fi
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$NEW_VERSION -f frontend/Dockerfile ./frontend
+          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$NEW_VERSION
