fix(build):for both of them

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -91,8 +91,8 @@ jobs:
         env:
           NEW_VERSION: ${{ env.NEW_VERSION }}
         run: |
-          if [ -z "$NEW_VERSION" ]; then
-            echo "Error: Version not set." && exit 1
+          if [[ -z "$NEW_VERSION" || "$NEW_VERSION" == "v" ]]; then
+            echo "Error: Version not set or invalid." && exit 1
           fi
           docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:$NEW_VERSION -f backend/Dockerfile ./backend
           docker push ${{ secrets.DOCKER_USERNAME }}/backend:$NEW_VERSION
@@ -119,8 +119,8 @@ jobs:
         env:
           NEW_VERSION: ${{ env.NEW_VERSION }}
         run: |
-          if [ -z "$NEW_VERSION" ]; then
-            echo "Error: Version not set." && exit 1
+          if [[ -z "$NEW_VERSION" || "$NEW_VERSION" == "v" ]]; then
+            echo "Error: Version not set or invalid." && exit 1
           fi
           docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:$NEW_VERSION -f frontend/Dockerfile ./frontend
           docker push ${{ secrets.DOCKER_USERNAME }}/frontend:$NEW_VERSION
